#ifndef __R2K_BATTLE_TYPES__
#define __R2K_BATTLE_TYPES__

// 적/아군의 위치
enum BatPos{
	BPOS_NORMAL,
	BPOS_BACKATTACK_HERO,
	BPOS_BACKATTACK_ENEMY,
	BPOS_SIDEATTACK_HERO,
	BPOS_SIDEATTACK_ENEMY
};

// 스택에 쌓이는 행동의 종류
enum BatActType{
	BAT_WAIT,

	BAT_ATTACK,
	BAT_ATTACKTWO,
	BAT_SKILL,
	BAT_ITEM,
	BAT_DEFENCE,
	BAT_ESCAPE,
	BAT_SELFDEST,
	BAT_CHANGE,
	BAT_VIEW, 
	BAT_GATHER_POWER,

	BAT_TURN_END,

	BAT_BATTLE_START,
	BAT_BATTLE_END,
	BAT_BATTLE_END_WAIT_RESULT
};

// 배틀이 어떻게 종료되었는지
enum BatEndType{
	BET_NotEnd,
	BET_Win,
	BET_Lose,
	BET_Escape,
	BET_Event
};


// 아군 캐릭터의 에니메이션(2003)
enum BatAnimationType {
	BMT_IDLE		= 0,
	BMT_RIGHT_ATK	= 1,
	BMT_LEFT_ATK	= 2,
	BMT_SPECIAL		= 3,
	BMT_DEAD		= 4,
	BMT_DAMAGED		= 5,
	BMT_ABNORMAL	= 6,
	BMT_DEFFENCE	= 7,
	BMT_LEFT_MOVE	= 8,
	BMT_RIGHT_MOVE	= 9,
	BMT_VICTORY		= 10,
	BMT_ITEM		= 11
};

// 이미지 노드의 에니메이션 종류(2003) 
enum BatCharType{
	BCT_MOVE_FRONT_WALK,
	BCT_MOVE_FRONT_WALK_TO_ENEMY,
	BCT_MOVE_FRONT_JUMP,
	BCT_MOVE_BACK_WALK,
	BCT_MOVE_BACK_WALK_FROM_ENEMY,
	BCT_MOVE_BACK_JUMP,

	BCT_WEAPON_FRONT,
	BCT_WEAPON_FRONT_ALL,
	BCT_WEAPON_BACK,
	BCT_WEAPON_BACK_ALL,

	BCT_EFFECT,
	BCT_ANIMATION,

	BCT_ETC_ACTION, 

	BCT_MOVE_ESCAPE
};

enum BatMenuPos{
	BMS_AUTO,			//0 BC
	BMS_HERO,			// ABCR
	BMS_ACTION,			//0ABCR
	BMS_TARGET_ENEMY,	//0ABCR
	BMS_TARGET_HERO,	//0ABCR
	BMS_ITEM,			// ABC
	BMS_SKILL,			// ABC
	BMS_SKILL_BY_ITEM,
	BMS_PROCESS			//0  
};

enum BatType{
	BTT_0	= -1,
	BTT_3A	= 0,
	BTT_3B	= 1,
	BTT_3C	= 2,
};

enum BatFinishType{
	BFT_NOT_WORK,
	BFT_VICTORY,
	BFT_DEFEAT,
	BFT_ESCAPE,
	BFT_EVENT
};

#endif